/* queries to insert all data into database. */
-- TODO:
INSERT INTO over_masteries(attribute, values)
VALUES (
('Attack Power Up',	[200, 300,400,500,600,700,800,1000]),
('HP Up',	[400,500,600,800,1000,1200,1600,2000]),
('Critical Hit Rate Up',	[0.02,0.04,0.06,0.08,0.1,0.12,0.16,0.2]),
('Stun Power Up',	[2,4,6,8,10,12,16,20]),
('Skill Damage Up',	[0.02,0.04,0.06,0.08,0.1,0.12,0.16,0.2]),
('Skybound Art Damage Up',	[0.02,0.04,0.06,0.08,0.1,0.12,0.16,0.2]),
('Chain Burst Damage Up',	[0.02,0.04,0.06,0.08,0.1,0.12,0.16,0.2]),
('Normal Attack Damage Cap Up',	[0.02,0.04,0.06,0.08,0.1,0.12,0.16,0.2]),
('Skill Damage Cap Up',	[0.02,0.04,0.06,0.08,0.1,0.12,0.16,0.2]),
('Skybound Art Damage Cap Up',	[0.02,0.04,0.06,0.08,0.1,0.12,0.16,0.2]),
('Healing Cap Up',	[0.02,0.04,0.06,0.08,0.1,0.12,0.16,0.2])
)
  
INSERT INTO weapons(weapon_name, weapon_user,	weapon_type)
VALUES (
'MAGNUM OPUS','Cagliostro','defender'),
'TRANSMIGRATION TOME','Cagliostro','ascension'),
'ARSHIVELLE','Cagliostro','executioner'),
'SACRED CODEX','Cagliostro','stinger'),
'DREAM ATLAS','Cagliostro','stunner'),
'ZOSIMOS','Cagliostro','terminus'),
'CLAIOMH SOLAIS','Charlotta','defender'),
'CLAIDHEAMH SOLUIS','Charlotta','ascension'),
'SAHRIVAR','Charlotta','executioner'),
'USHUMGAL','Charlotta','stinger'),
'ARONDIGHT','Charlotta','stunner'),
'GALATINE','Charlotta','terminus'),
'DREYSE','Eugen','defender'),
'AK-4A','Eugen','ascension'),
'CLARION','Eugen','executioner'),
'LEVIATHAN MUZZLE','Eugen','stinger'),
'MATCHLOCK','Eugen','stunner'),
'DRACONIC FIRE','Eugen','terminus'),
'GEISTERPEITSCHE','Ferry','defender'),
'ERINNERUNG','Ferry','ascension'),
'LIVE WIRE','Ferry','executioner'),
'FLAME LIT CURL','Ferry','stinger'),
'LEATHER BELT','Ferry','stunner'),
'ETHEREAL LASHER','Ferry','terminus'),
'BRAHMA GAUNTLET','Ghandagoza','defender'),
'GOLDEN FISTS OF URA','Ghandagoza','ascension'),
'ARKAB','Ghandagoza','executioner'),
'CRIMSON FINGER','Ghandagoza','stinger'),
'ROPE KNUCKLES','Ghandagoza','stunner'),
'SKY PIERCER','Ghandagoza','terminus'),
'RAGNAROK','Id','defender'),
'SUSANOO','Id','ascension'),
'ECKE SACHS','Id','executioner'),
'PREMIUM SWORD','Id','stinger'),
'AVIAETH FAUSSART','Id','stunner'),
'SWORD OF BAHAMUT','Id','terminus'),
'LITTLE WITCH SCEPTER','Io','defender'),
'GAMBANTEINN','Io','ascension'),
'TUPSIMATI','Io','executioner'),
'COLOSSUS CANE OMEGA','Io','stinger'),
'ZHEZL','Io','stunner'),
'CADUCEUS','Io','terminus'),
'RUKALSA','Katalina','defender'),
'MURGLEIS','Katalina','ascension'),
'EPHEMERON','Katalina','executioner'),
'LUMINIERA SWORD OMEGA','Katalina','stinger'),
'FLAME RAPIER','Katalina','stunner'),
'BLUTGANG','Katalina','terminus'),
'ALTACHIARA','Lancelot','defender'),
'KNIGHT OF ICE','Lancelot','ascension'),
'BLANC COMME NEIGE','Lancelot','executioner'),
'VEGALTA','Lancelot','stinger'),
'HOARFROST BLADE PERSIUS','Lancelot','stunner'),
'DAMASCUS KNIFE','Lancelot','terminus'),
'NAKAMAKI NODACHI','Narmaya','defender'),
'VENUSTAS','Narmaya','ascension'),
'BLADE OF PURIFICATION','Narmaya','executioner'),
'FLUORITHIUM BLADE','Narmaya','stinger'),
'KOTETSU','Narmaya','stunner'),
'AMENO HABAKIRI','Narmaya','terminus'),
'FLAMBERGE','Percival','defender'),
'LORD OF FLAMES','Percival','ascension'),
'ANTWERP','Percival','executioner'),
'JOYEUSE','Percival','stinger'),
'LOHENGRIN','Percival','stunner'),
'GOTTFRIED','Percival','terminus'),
'FLINTSPIKE','Rackam','defender'),
'BENEDIA','Rackam','ascension'),
'STORMCLOUD','Rackam','executioner'),
'TIAMAT BOLT OMEGA','Rackam','stinger'),
'WHEELLOCK AXE','Rackam','stunner'),
'FREIKUGEL','Rackam','terminus'),
'EGOISM','Rosetta','defender'),
'LOVE ETERNAL','Rosetta','ascension'),
'CORTANA','Rosetta','executioner'),
'ROSE CRYSTAL KNIFE','Rosetta','stinger'),
'SWORD BREAKER','Rosetta','stunner'),
'DAGGER OF BAHAMUT CODA','Rosetta','terminus'),
'INTEGRITY','Siegfried','defender'),
'ASCALON','Siegfried','ascension'),
'WINDHOSE','Siegfried','executioner'),
'HRUNTING','Siegfried','stinger'),
'BROADSWORD OF EARTH','Siegfried','stunner'),
'BALMUNG','Siegfried','terminus'),
"TRAVELLER'S SWORD",'The Captain','defender'),
'SWORD OF EOS','The Captain','ascension'),
'ULTIMA SWORD','The Captain','executioner'),
'ALBACORE BLADE','The Captain','stinger'),
'DURANDAL','The Captain','stunner'),
'SEVEN-STAR SWORD','The Captain','terminus'),
'ALABARDA','Vane','defender'),
'TREUER KRIEGER','Vane','ascension'),
'BLOSSOM AXE','Vane','executioner'),
'UKONVASARA','Vane','stinger'),
'SWAN','Vane','stunner'),
'MJOLNIR','Vane','terminus'),
'GREAT SCYTHE GRYNOTH','Vaseraga','defender'),
'WURTZITE SCYTHE','Vaseraga','ascension'),
'COSMIC SCYTHE','Vaseraga','executioner'),
'SOUL EATER','Vaseraga','stinger'),
'ALSARAV','Vaseraga','stunner'),
'ERESHKIGAL','Vaseraga','terminus'),
'KIKU-ICHIMONJI','Yodarha','defender'),
'FUDO-KUNIYUKI','Yodarha','ascension'),
'XENO PHANTOM DEMON BLADE','Yodarha','executioner'),
'HIGURASHI','Yodarha','stinger'),
'ASURA','Yodarha','stunner'),
'SWORDFISH','Yodarha','terminus'),
'SPEAR OF ARVESS','Zeta','defender'),
'BRIONAC','Zeta','ascension'),
'HUANGLONG SPEAR','Zeta','executioner'),
'GISLA','Zeta','stinger'),
'SUNSPOT SPEAR','Zeta','stunner'),
'GAE BULG','Zeta','terminus')
)
